### ISSUE TITLE
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

### ISSUE THREAD

**Issue by ankurk91** [medz/webpack-laravel-mix-manifest#14]
* Webpack v5.0.0
* Node.js v12.18.4

I see this warning in console.
```
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
```

Is it possible to prevent this warning in webpack 5?

**Comment by medz** [comment]
Okay~ I haven't watched WebPack 5 recently, I will check it later and make compatibility

**Comment by medz** [comment]
@ankurk91 Hi, because webpack5 has major changes, the most important thing is that the Types export has changed. This plug-in is written in TypeScript, and I will take into account the type export method of webpack4. So version 3.0.0 was released for webpack5 adaptation.

**Comment by ankurk91** [comment]
@medz 
Thanks for the update 😄
