### ISSUE TITLE
Duplicated paths when using  path based entries

### ISSUE THREAD

**Issue by canvasplay** [medz/webpack-laravel-mix-manifest#18]
Hi! Let me thank you for creating this plugin first of all ;)

I'm facing a "bug" using v2.2 and path based entries, it duplicates the path reference for some reason.

I'm using the following code:
````
const path = require('path');
const { WebpackLaravelMixManifest } = require('webpack-laravel-mix-manifest');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

module.exports = {
    mode: 'none',
    entry: {
        'main': path.resolve(__dirname, '.../main.js'),
        'path/to/main': path.resolve(__dirname, '.../path/to/somewhere/else/main.js'),
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name]-[hash].js',
    },
    plugins: [
        new CleanWebpackPlugin,
        new WebpackLaravelMixManifest,
    ]
};
````

Gives the following output:
``````
{
  "/main.js": "/main-3f663f8ee172ebfa8218.js"
  "/path/to/path/to/main.js": "/path/to/main-bd6aa1bfdc4dd1131a4b.js"
}
``````

Note the difference when using an entry with the output at root of public path and when the output is nested in some path.

Everything else in the webpack process is working as expected except the manifest output, for this reason I'm guessing it could be a bug.

Thanks!

**Comment by medz** [comment]
It is indeed a bug. I did not consider this situation when creating the plugin. I will soon do a related unit test and fix it.

**Comment by medz** [comment]
@canvasplay Hey,

The bug has been fixed, I released it to version 3.0.3 and added a special unit test.

https://www.npmjs.com/package/webpack-laravel-mix-manifest

**Comment by medz** [comment]
Unit test code 👉  [manifest.test.ts#L23](https://github.com/medz/webpack-laravel-mix-manifest/blob/master/__tests__/manifest.test.ts#L23)

**Comment by medz** [comment]
😂Sorry, v2.2.x has not been fixed yet, please wait

**Comment by medz** [comment]
v2.2.2 version published

**Comment by canvasplay** [comment]
wow! Awesomely fast!

Thanks you so much!
