### ISSUE TITLE
Release v2.0 on npm

### ISSUE THREAD

**Issue by ankurk91** [medz/webpack-laravel-mix-manifest#2]
Hi, there

I see version 2.0 was released on Github
https://github.com/medz/webpack-laravel-mix-manifest/releases/tag/v2.0.0

but not on npm
https://www.npmjs.com/package/webpack-laravel-mix-manifest

The latest version on npm is still v1.0.6

Thanks.

**Comment by medz** [comment]
Released, Thanks. :)
